# Generated by Django 5.0.6 on 2024-07-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapplication', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
